### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by stennie**
Some improvements based on trying to follow the README to get started.

### CODE REVIEW

**Comment by webchick** [comment]
Oh, this is very helpful! I like that we don't assume people don't what the heck `pip` / `pipenv` are and how to use them. 👍 

One quick suggestion: I like how you explicitly tell people how to install using `pip`, can we do the same for `pipenv`? Like:

> To install GDELT Tools using `pipenv`:
> 
> ```
>     pipenv install Pipfile
> ```

(I assume? This seemed to do something for me, anyway. :D)

> And then [whatever you're supposed to do with `pipenv shell`].

And then, just a question: is `pip3` / `python3` the proper way to do things, even on modern machines? It feels so clunky. ;( I ended up following the instructions here https://opensource.com/article/19/5/python-3-default-mac to make it just regular "python" and "pip."

**Comment by stennie** [comment]
>  I like how you explicitly tell people how to install using pip, can we do the same for pipenv? 

This is already in the README under "Install requirements using Pipenv (recommended)". You first need to install `pipenv`, and can then run `pipenv install`(which defaults to using`Pipfile`, if found in the current directory.

> is pip3 / python3 the proper way to do things, even on modern machines?

Unfortunately, yes. The main challenge is that macOS prior to Monterey still ships with Python 2.7 as the system default Python. If you install Python 3 but do not have it as the default in your path, `python` will be Python 2.7. [PEP 394](https://peps.python.org/pep-0394/) ensures that `python3` and `pip3` are referring to Python 3.

We could add more info here, like checking the output of `python --version` and `which python`, but the simplest fix that I've learned from maintaining other Python tools is to recommend `python3` and `pip3`.

If your default Python is indeed Python 3, `python` and `pip` will do the right thing. However, `python3` and `pip3` should always have the expected outcome.

**Comment by webchick** [comment]
Oh, nice! In that case, LGTM. 👍

**Comment by jdrumgoole** [comment]
The right answer is to build a proper python package. I will do that next
week.

**Comment by jdrumgoole** [comment]
I think most of these issues are fixed with the latest release Stennie. Can you give it a spin?

https://pypi.org/project/gdelttools/

**Pull request closed without merging**
